import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import { Inter, Poppins, Merriweather, Kumbh_Sans, Nunito } from 'next/font/google';
import './globals.css';
import { ErrorBoundary } from '@/ui/errors/error-boundary';
import { AppProvider } from './provider';

const merriweather = Merriweather({
  variable: '--font-merriweather',
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
});
const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
});
const kumbhSans = Kumbh_Sans({
  variable: '--font-kumbhSans',
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
});
const nunito = Nunito({
  variable: '--font-nunito',
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.variable} ${inter.variable} ${poppins.variable} ${kumbhSans.variable} ${nunito} antialiased flex flex-col min-h-full`}
      >
        <ErrorBoundary>
          <AppProvider>
            <div className="flex min-h-full flex-1 flex-col bg-[#f5f5f5] ">
              {children}
            </div>
            <Toaster position="top-center" offset={10} />
          </AppProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
